#!/usr/bin/env bash
# Execute a Jupyter notebook on Kaggle's Kernel Backend (KKB) using kaggle-cli.
#
# Workflow:
#   1. kaggle kernels push   — upload notebook and trigger execution
#   2. kaggle kernels logs -f — follow live logs until the stream closes
#   3. kaggle kernels output  — download execution results
#
# Prerequisites:
#   `uv sync --locked` completed in the repository
#   Credentials configured via `uv run kaggle auth login`, ~/.kaggle/access_token, KAGGLE_API_TOKEN, or legacy ~/.kaggle/kaggle.json
#   kernel-metadata.json in the same directory as the notebook
#
# Usage:
#   bash .agents/skills/kaggle-platform/modules/kllm/scripts/cli_execute.sh <notebook-dir> <kernel-slug> [output-dir]
#
# Arguments:
#   notebook-dir  — directory containing notebook + kernel-metadata.json
#   kernel-slug   — e.g., "username/kernel-name"
#   output-dir    — directory to save output (default: /tmp/kaggle-output/<kernel-slug>)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../../.." && pwd)"
KAGGLE=(uv run --project "${REPO_ROOT}" kaggle)

NOTEBOOK_DIR="${1:?Usage: cli_execute.sh <notebook-dir> <kernel-slug> [output-dir]}"
KERNEL_SLUG="${2:?Usage: cli_execute.sh <notebook-dir> <kernel-slug> [output-dir]}"
if [[ ! "${KERNEL_SLUG}" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]]; then
    echo "[FAIL] kernel slug '${KERNEL_SLUG}' is not in the expected owner/name form" >&2
    exit 2
fi
KERNEL_PATH_SLUG="${KERNEL_SLUG//\//-}"
OUTPUT_DIR="${3:-/tmp/kaggle-output/${KERNEL_PATH_SLUG}}"

echo "============================================================"
echo "Step 0: Prepare kernel-metadata.json"
echo "============================================================"
echo ""
echo "Before pushing, edit kernel-metadata.json and replace YOUR_USERNAME"
echo "with your actual Kaggle username. The metadata file must be in the"
echo "same directory as the notebook."
echo ""
echo "Required fields in kernel-metadata.json:"
echo '  "id": "username/kernel-slug"'
echo '  "code_file": "sample_notebook.ipynb"'
echo '  "language": "python"'
echo '  "kernel_type": "notebook"'
echo ""

echo "============================================================"
echo "Step 1: Push notebook to Kaggle (triggers execution)"
echo "============================================================"

# Push the notebook — this uploads the code and starts execution on KKB
"${KAGGLE[@]}" kernels push -p "${NOTEBOOK_DIR}"

echo "Notebook pushed. Execution started on KKB."
echo ""

echo "============================================================"
echo "Step 2: Follow execution logs"
echo "============================================================"

# CLI 2.2.3 live SSE is the primary monitoring path. `kernels status` can
# return GetKernelSessionStatus 500 and must not gate completion.
"${KAGGLE[@]}" kernels logs -f "${KERNEL_SLUG}"
echo "Live log stream closed. Inspect the final log or Kaggle UI if completion is unclear."

echo ""
echo "============================================================"
echo "Step 3: Download execution output"
echo "============================================================"

# Download the output files generated by the notebook. For CV-only runs where
# no output file inspection is needed, use `kaggle kernels logs -f` directly
# instead of this full helper.
mkdir -p "${OUTPUT_DIR}"
"${KAGGLE[@]}" kernels output "${KERNEL_SLUG}" \
    --path "${OUTPUT_DIR}"

echo "Output downloaded to ${OUTPUT_DIR}/"
ls -la "${OUTPUT_DIR}/"

echo ""
echo "============================================================"
echo "Optional: Pull the executed notebook (with cell outputs)"
echo "============================================================"

# Pull the notebook source (includes rendered outputs after execution)
"${KAGGLE[@]}" kernels pull "${KERNEL_SLUG}" \
    --path "${OUTPUT_DIR}/notebook-source" \
    --metadata

echo "Notebook source pulled to ${OUTPUT_DIR}/notebook-source/"
ls -la "${OUTPUT_DIR}/notebook-source/"
