"""Phase 5: Streak badges (~4 badges).

Runs today's streak actions and generates a reusable daily script:
  - 7-Day Login Streak
  - 30-Day Login Streak
  - Submission Streak (7 days)
  - Super Submission Streak (30 days)

The script is generated for the user to schedule themselves if desired.
No cron jobs or launchd plists are installed automatically. A single run leaves
the badges in progress; it never records a multi-day badge as earned.
"""

import platform
import stat
import subprocess
from pathlib import Path

from badge_tracker import set_status, should_attempt
from utils import REPO_ROOT, STATE_DIR, get_kaggle_cli

DAILY_SCRIPT_PATH = STATE_DIR / "daily_streak.sh"


def _create_daily_script() -> Path:
    """Create the daily streak script without credentials."""
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    submission_file = STATE_DIR / "gender_submission.csv"

    script = f"""#!/usr/bin/env bash
# Daily Kaggle streak script — auto-generated by badge-collector
# Credentials follow the repository's canonical Kaggle registration guide.

set -euo pipefail

REPO_ROOT="{REPO_ROOT}"
STATE_DIR="{STATE_DIR}"
mkdir -p "$STATE_DIR"

# 1. API activity
uv run --project "$REPO_ROOT" kaggle datasets list --page-size 1 > /dev/null

# 2. Refresh the official Titanic example submission and submit it
SUBMISSION="{submission_file}"
uv run --project "$REPO_ROOT" kaggle competitions download titanic \\
    --file gender_submission.csv \\
    --path "$STATE_DIR" \\
    --force \\
    --quiet
uv run --project "$REPO_ROOT" kaggle competitions submit \\
    -c titanic \\
    -f "$SUBMISSION" \\
    -m "Daily streak submission $(date +%Y-%m-%d)" \\
    > /dev/null

echo "[$(date)] Streak actions completed"
"""
    DAILY_SCRIPT_PATH.write_text(script)
    DAILY_SCRIPT_PATH.chmod(stat.S_IRWXU)
    return DAILY_SCRIPT_PATH


def _run_today(kaggle_cli: tuple[str, ...]) -> bool:
    """Run today's API activity and Titanic submission."""
    print("  Running today's streak actions...")

    result = subprocess.run(
        [*kaggle_cli, "datasets", "list", "--page-size", "1"],
        capture_output=True,
        text=True,
    )
    api_ok = result.returncode == 0
    if api_ok:
        print("    API activity: OK")
    else:
        print(f"    API activity: FAILED ({result.stderr.strip()})")

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    submission_file = STATE_DIR / "gender_submission.csv"
    download = subprocess.run(
        [
            *kaggle_cli,
            "competitions",
            "download",
            "titanic",
            "--file",
            submission_file.name,
            "--path",
            str(STATE_DIR),
            "--force",
            "--quiet",
        ],
        capture_output=True,
        text=True,
    )
    submission_ok = False
    if download.returncode == 0 and submission_file.is_file():
        result = subprocess.run(
            [
                *kaggle_cli,
                "competitions",
                "submit",
                "-c",
                "titanic",
                "-f",
                str(submission_file),
                "-m",
                "Daily streak submission",
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print("    Titanic submission: OK")
            submission_ok = True
        else:
            print(f"    Titanic submission: FAILED ({result.stderr.strip()})")
    else:
        print(f"    Titanic submission: FAILED to download {submission_file.name}")

    return api_ok and submission_ok


def _print_scheduling_instructions(script_path: Path) -> None:
    """Print instructions for user-controlled daily scheduling."""
    system = platform.system()

    print("\n  --- Manual scheduling instructions ---")
    print(f"  Daily script created at: {script_path}")
    print()

    if system == "Darwin":
        print("  To schedule on macOS (launchd):")
        print("    1. Create a plist at ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print(f"       with ProgramArguments pointing to: /bin/bash {script_path}")
        print("    2. Load it: launchctl load ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print()
        print("  Or use cron:")
        print("    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")
    else:
        print("  To schedule on Linux (cron):")
        print("    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")

    print()
    print("  Credentials follow the canonical registration guide and")
    print("  KAGGLE_USERNAME must be configured for resource ownership.")
    print("  Badges can be earned only after 7/30 days of successful daily actions.")


def run(username: str) -> tuple[int, int]:
    """Run today's actions and generate the script.

    Return automatic action attempt/success counts. A single run cannot verify
    any multi-day badge.
    """
    badge_ids = [
        "seven_day_login_streak",
        "thirty_day_login_streak",
        "submission_streak",
        "super_submission_streak",
    ]

    actionable = [badge_id for badge_id in badge_ids if should_attempt(badge_id)]
    if not actionable:
        print("  No streak prerequisite actions need to be repeated")
        return 0, 0

    print("\n  --- Phase 5: Streak badges ---")

    actions_completed = _run_today(get_kaggle_cli())
    script_path = _create_daily_script()
    _print_scheduling_instructions(script_path)

    for badge_id in actionable:
        if actions_completed:
            set_status(
                badge_id,
                "attempting",
                "today's actions done — badge remains pending until the full streak",
            )
        else:
            set_status(
                badge_id,
                "failed",
                "today's API or submission action failed",
            )

    return 1, int(actions_completed)
